"""Curated public barrel for the unofficial Codex Agent SDK.

Happy-path imports should come from this module:

- ``query()`` for one-shot scripted use
- ``CodexSDKClient`` for stateful thread workflows
- ``AppServerClient`` for low-level JSON-RPC access
- ``CodexOptions`` and ``AppServerConfig`` for configuration

Import policy:

- names re-exported here are the supported public API
- ``errors`` and ``options`` remain stable support modules for focused imports
- lower-level layers under ``transport``, ``rpc``, ``protocol``, ``generated``,
  and ``testing`` stay importable but are not part of the curated root surface
"""

from .approvals import ApprovalDecision, ApprovalRequest
from .client import AppServerClient, CodexSDKClient
from .errors import (
    AlreadyInitializedError,
    ApprovalCallbackError,
    ApprovalError,
    ApprovalRequestExpiredError,
    ClientStateError,
    CodexError,
    CodexNotFoundError,
    CodexTimeoutError,
    DuplicateRequestIdError,
    DuplicateResponseError,
    InvalidApprovalDecisionError,
    JsonRpcError,
    JsonRpcInternalError,
    JsonRpcInvalidParamsError,
    JsonRpcInvalidRequestError,
    JsonRpcMethodNotFoundError,
    JsonRpcParseError,
    JsonRpcServerError,
    LateResponseError,
    MessageDecodeError,
    NotInitializedError,
    ProcessExitError,
    ProtocolError,
    RequestCorrelationError,
    RequestTimeoutError,
    ResponseValidationError,
    RetryableOverloadError,
    RetryBudgetExceededError,
    ShutdownError,
    ShutdownTimeoutError,
    StartupError,
    StartupTimeoutError,
    TransportClosedError,
    TransportError,
    TransportWriteError,
    UnexpectedMessageError,
    UnknownResponseIdError,
    is_retryable_error,
    map_jsonrpc_error,
)
from .events import (
    AgentTextDeltaEvent,
    ApprovalRequestedEvent,
    CommandOutputDeltaEvent,
    ItemCompletedEvent,
    ItemStartedEvent,
    RawNotificationEvent,
    RawServerRequestEvent,
    ReasoningTextDeltaEvent,
    ThreadStatusChangedEvent,
    TokenUsageUpdatedEvent,
    TurnCompletedEvent,
    TurnEvent,
    TurnStartedEvent,
)
from .options import (
    DEFAULT_SHUTDOWN_TIMEOUT_SECONDS,
    DEFAULT_STARTUP_TIMEOUT_SECONDS,
    DEFAULT_TIMEOUT_POLICY,
    AppServerConfig,
    CodexOptions,
    TimeoutPolicy,
)
from .query import query
from .results import TurnHandle, TurnResult

__all__ = [
    "ApprovalDecision",
    "ApprovalRequest",
    "AppServerClient",
    "AppServerConfig",
    "AgentTextDeltaEvent",
    "AlreadyInitializedError",
    "ApprovalCallbackError",
    "ApprovalError",
    "ApprovalRequestExpiredError",
    "ApprovalRequestedEvent",
    "ClientStateError",
    "CodexError",
    "CodexNotFoundError",
    "CodexOptions",
    "CodexSDKClient",
    "CodexTimeoutError",
    "CommandOutputDeltaEvent",
    "DEFAULT_SHUTDOWN_TIMEOUT_SECONDS",
    "DEFAULT_STARTUP_TIMEOUT_SECONDS",
    "DEFAULT_TIMEOUT_POLICY",
    "DuplicateRequestIdError",
    "DuplicateResponseError",
    "InvalidApprovalDecisionError",
    "ItemCompletedEvent",
    "ItemStartedEvent",
    "JsonRpcError",
    "JsonRpcInternalError",
    "JsonRpcInvalidParamsError",
    "JsonRpcInvalidRequestError",
    "LateResponseError",
    "JsonRpcMethodNotFoundError",
    "JsonRpcParseError",
    "JsonRpcServerError",
    "MessageDecodeError",
    "NotInitializedError",
    "ProcessExitError",
    "ProtocolError",
    "query",
    "RawNotificationEvent",
    "RawServerRequestEvent",
    "ReasoningTextDeltaEvent",
    "RequestCorrelationError",
    "RequestTimeoutError",
    "ResponseValidationError",
    "RetryBudgetExceededError",
    "RetryableOverloadError",
    "ShutdownError",
    "ShutdownTimeoutError",
    "StartupError",
    "StartupTimeoutError",
    "ThreadStatusChangedEvent",
    "TimeoutPolicy",
    "TokenUsageUpdatedEvent",
    "TransportClosedError",
    "TransportError",
    "TransportWriteError",
    "TurnCompletedEvent",
    "TurnEvent",
    "TurnHandle",
    "TurnResult",
    "TurnStartedEvent",
    "UnknownResponseIdError",
    "UnexpectedMessageError",
    "is_retryable_error",
    "map_jsonrpc_error",
]
