from __future__ import annotations

import importlib
import importlib.util
import sys
import unittest
from pathlib import Path
from typing import Any

from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED_REGISTRY_PATH = (
    REPO_ROOT / "src" / "codex_agent_sdk" / "generated" / "stable_server_request_registry.py"
)
CODEGEN_SCRIPT_PATH = REPO_ROOT / "scripts" / "generate_protocol_models.py"


def load_codegen_script_module() -> object:
    spec = importlib.util.spec_from_file_location("generate_protocol_models", CODEGEN_SCRIPT_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load module spec for {CODEGEN_SCRIPT_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class GeneratedServerRequestRegistryTests(unittest.TestCase):
    codegen_script: Any
    protocol_server_requests: Any
    registry: Any

    @classmethod
    def setUpClass(cls) -> None:
        cls.codegen_script = load_codegen_script_module()
        cls.protocol_server_requests = importlib.import_module(
            "codex_agent_sdk.protocol.server_requests"
        )
        cls.registry = importlib.import_module(
            "codex_agent_sdk.generated.stable_server_request_registry"
        )

    def test_generation_script_declares_server_request_registry_output(self) -> None:
        self.assertEqual(
            self.codegen_script.SERVER_REQUEST_REGISTRY_OUTPUT_PATH,
            GENERATED_REGISTRY_PATH,
        )

        content = GENERATED_REGISTRY_PATH.read_text(encoding="utf-8")
        self.assertTrue(content.startswith("# generated by scripts/generate_protocol_models.py:"))
        self.assertIn("#   schema-artifact: stable", content)
        self.assertIn("#   schema-path: tests/fixtures/schema_snapshots/stable/", content)
        self.assertIn("#   schema-sha256:", content)
        self.assertIn("#   generator-version-pin: datamodel-code-generator==", content)
        self.assertIn("#   registry-entry-count:", content)
        self.assertIn("#   registry-specs-sha256:", content)
        self.assertIn("class StableServerRequestRegistryEntry:", content)
        self.assertIn("SERVER_REQUEST_METHODS = (", content)
        self.assertIn("protocol_server_requests", content)

    def test_generated_registry_matches_configured_specs_and_models(self) -> None:
        expected_by_method = {
            spec.method: spec.params_model_name
            for spec in self.codegen_script.SERVER_REQUEST_REGISTRY_SPECS
        }

        self.assertEqual(
            tuple(sorted(expected_by_method)),
            self.registry.SERVER_REQUEST_METHODS,
        )
        self.assertEqual(
            set(expected_by_method),
            set(self.registry.SERVER_REQUEST_REGISTRY),
        )

        for method, entry in self.registry.SERVER_REQUEST_REGISTRY.items():
            with self.subTest(method=method):
                expected_params_name = expected_by_method[method]
                self.assertEqual(entry.method, method)
                self.assertEqual(entry.params_model_name, expected_params_name)
                self.assertIs(
                    entry.params_model,
                    getattr(self.protocol_server_requests, expected_params_name),
                )
                self.assertTrue(issubclass(entry.params_model, BaseModel))

    def test_generated_registry_covers_representative_approval_and_input_methods(self) -> None:
        representative_methods = {
            "item/commandExecution/requestApproval": "CommandExecutionApprovalRequestParams",
            "item/fileChange/requestApproval": "FileChangeApprovalRequestParams",
            "item/permissions/requestApproval": "PermissionsRequestApprovalParams",
            "item/tool/requestUserInput": "ToolRequestUserInputParams",
            "mcpServer/elicitation/request": "McpServerElicitationRequestParams",
            "item/tool/call": "DynamicToolCallRequestParams",
        }

        for method, expected_model_name in representative_methods.items():
            with self.subTest(method=method):
                entry = self.registry.get_server_request_registry_entry(method)
                self.assertIsNotNone(entry)
                assert entry is not None
                self.assertEqual(entry.params_model_name, expected_model_name)


if __name__ == "__main__":
    unittest.main()
