from __future__ import annotations

import importlib
import importlib.util
import sys
import unittest
from pathlib import Path
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED_REGISTRY_PATH = (
    REPO_ROOT / "src" / "codex_agent_sdk" / "generated" / "stable_notification_registry.py"
)
CODEGEN_SCRIPT_PATH = REPO_ROOT / "scripts" / "generate_protocol_models.py"


def load_codegen_script_module() -> object:
    spec = importlib.util.spec_from_file_location("generate_protocol_models", CODEGEN_SCRIPT_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load module spec for {CODEGEN_SCRIPT_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class GeneratedNotificationRegistryTests(unittest.TestCase):
    generated: Any
    registry: Any
    codegen_script: Any

    @classmethod
    def setUpClass(cls) -> None:
        cls.generated = importlib.import_module("codex_agent_sdk.generated.stable")
        cls.registry = importlib.import_module(
            "codex_agent_sdk.generated.stable_notification_registry"
        )
        cls.codegen_script = load_codegen_script_module()

    def test_generation_script_declares_notification_registry_output(self) -> None:
        self.assertEqual(
            self.codegen_script.NOTIFICATION_REGISTRY_OUTPUT_PATH,
            GENERATED_REGISTRY_PATH,
        )

        content = GENERATED_REGISTRY_PATH.read_text(encoding="utf-8")
        self.assertTrue(content.startswith("# generated by scripts/generate_protocol_models.py:"))
        self.assertNotIn("timestamp:", "\n".join(content.splitlines()[:3]))
        self.assertIn("class StableNotificationRegistryEntry:", content)
        self.assertIn("SERVER_NOTIFICATION_METHODS = (", content)
        self.assertIn(
            "SERVER_NOTIFICATION_REGISTRY: dict[str, StableNotificationRegistryEntry]", content
        )

    def test_generated_registry_matches_generated_notification_wrappers(self) -> None:
        expected_by_method: dict[str, tuple[str, str]] = {}

        for name, value in vars(self.generated).items():
            if name == "ServerNotification" or not name.startswith("ServerNotification"):
                continue
            if not isinstance(value, type) or not issubclass(value, BaseModel):
                continue

            model_fields = getattr(value, "model_fields", {})
            method_field = model_fields.get("method")
            params_field = model_fields.get("params")
            if method_field is None or params_field is None:
                continue

            method_annotation = method_field.annotation
            self.assertEqual(get_origin(method_annotation), Literal)
            method_args = get_args(method_annotation)
            self.assertEqual(len(method_args), 1)
            self.assertIsInstance(method_args[0], str)
            params_annotation = params_field.annotation
            self.assertTrue(isinstance(params_annotation, type))
            self.assertTrue(issubclass(params_annotation, BaseModel))

            expected_by_method[method_args[0]] = (name, params_annotation.__name__)

        self.assertEqual(
            tuple(sorted(expected_by_method)),
            self.registry.SERVER_NOTIFICATION_METHODS,
        )
        self.assertEqual(
            set(expected_by_method),
            set(self.registry.SERVER_NOTIFICATION_REGISTRY),
        )

        for method, entry in self.registry.SERVER_NOTIFICATION_REGISTRY.items():
            with self.subTest(method=method):
                expected_envelope_name, expected_params_name = expected_by_method[method]
                self.assertEqual(entry.method, method)
                self.assertEqual(entry.envelope_model_name, expected_envelope_name)
                self.assertEqual(entry.params_model_name, expected_params_name)
                self.assertIs(entry.envelope_model, getattr(self.generated, expected_envelope_name))
                self.assertIs(entry.params_model, getattr(self.generated, expected_params_name))

    def test_generated_registry_covers_representative_methods(self) -> None:
        representative_methods = {
            "thread/started": "ThreadStartedNotification",
            "turn/started": "TurnStartedNotification",
            "item/started": "ItemStartedNotification",
            "item/agentMessage/delta": "AgentMessageDeltaNotification",
            "turn/completed": "TurnCompletedNotification",
        }

        for method, expected_model_name in representative_methods.items():
            with self.subTest(method=method):
                entry = self.registry.get_server_notification_registry_entry(method)
                self.assertIsNotNone(entry)
                assert entry is not None
                self.assertEqual(entry.params_model_name, expected_model_name)


if __name__ == "__main__":
    unittest.main()
